"""
Django settings for hms project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from decouple import config



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(zm7qyx@d=l5-4l!!!@ziv4o&a3_8&$)1^^+(qy*)os!2#5q8l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',  #to configure admin
    'django_ckeditor_5',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base',
    'doctor',
    'patient',
    'userauths',
    'store',
    'cart',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hms.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

CLINIC_LAT = 33.6844    
CLINIC_LNG = 73.0479    

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or your mail server
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'taimoormunawar974@gmail.com'
EMAIL_HOST_PASSWORD = 'aeik opat xuin cvte'
DEFAULT_FROM_EMAIL =  'Hanisha Homeo Clinic <taimoormunawar974@gmail.com>'



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT=os.path.join(BASE_DIR, "staticfiles")

STATICFILES_DIRS = [os.path.join(BASE_DIR , "static")]

MEDIA_URL= '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
CKEDITOR_UPLOAD_PATH = "uploads/"

COHERE_API_KEY = config("COHERE_API_KEY")


LOGIN_URL = '/'

LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL ="userauths.User"

MESSAGE_TAGS = {
    messages.ERROR: "danger"
}



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
JAZZMIN_SETTINGS = {
    # Branding
    "site_brand": "Hanisha Homeo Clinic",
    "site_title": "HHC Admin",
    "site_header": "Hanisha Homeo Clinic Admin",
    "welcome_sign": "Welcome to HHC — Manage with Ease",
    "copyright": "© All Rights Reserved 2025",

    "order_with_respect_to": [
        "base.appointment",
        "base.medicalrecord",
        "base.prescription",
        "base.service",
        "base.medicine",
        "base.cart",
        "base.cartitem",
        "base.blog",
        "base.blogcategory",
        "base.userquery",
        "auth.user",
    ],

    # Font Awesome Icons
    "icons": {
        "admin.LogEntry": "fas fa-clipboard-list",
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user-shield",

        "base.appointment": "fas fa-calendar-check",
        "base.prescription": "fas fa-prescription-bottle-alt",
        "base.service": "fas fa-stethoscope",
        "base.medicine": "fas fa-pills",
        "base.cart": "fas fa-shopping-cart",
        "base.cartitem": "fas fa-cart-plus",
        "base.blog": "fas fa-blog",
        "base.blogcategory": "fas fa-folder-open",
        "base.contact": "fas fa-envelope-open-text",
        "base.userquery": "fas fa-question-circle",

        "cart.cartitem": "fas fa-cart-plus",
        "cart.cart": "fas fa-shopping-cart",
        "cart.orderitem": "fas fa-box",
        "cart.order": "fas fa-file-invoice-dollar",

        "doctor.doctor": "fas fa-user-md",
        "doctor.notification": "fas fa-bell",

        "patient.notification": "fas fa-bell",
        "patient.patient": "fas fa-procedures",

        "store.medicine": "fas fa-pills",

        "userauths.user": "fas fa-user",
    },

    # Custom Links
    "custom_links": {
        "base.appointment": [
            {
                "name": "Today's Appointments",
                "url": "appointments_today",
                "icon": "fas fa-calendar-day",
                "permissions": ["base.view_appointment"]
            }
        ],
    },

    # UI Tweaks
    "show_ui_builder": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "changeform_format": "horizontal_tabs",
}


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-danger",
    "navbar": "navbar-primary navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme": "cerulean",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
