# Generated by Django 5.2.2 on 2025-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Appointment Booked', 'Appointment Booked'), ('Appointment Cancelled', 'Appointment Cancelled'), ('Prescription Added', 'Prescription Added'), ('Order Placed', 'Order Placed')], max_length=100),
        ),
    ]
