# Generated by Django 4.2.2 on 2025-06-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
