# Generated by Django 5.2.2 on 2025-06-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_prescription_created_at_prescription_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
