# Generated by Django 5.2.2 on 2025-06-28 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_cartitem_cart_remove_cartitem_medicine_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
