# Generated by Django 5.2.2 on 2025-06-28 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_medicalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='appointment',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='LabTest',
        ),
    ]
