# Generated by Django 5.2.2 on 2025-07-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_appointment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
