# Generated by Django 4.2.2 on 2025-06-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_doctor_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='time',
        ),
    ]
