# Generated by Django 5.2.2 on 2025-06-27 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_doctor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='country',
        ),
    ]
